on:
  issues:
    types: [labeled]

jobs:
  automate_invite:
    runs-on: ubuntu-latest
    steps:
      - name: Invite-on-label
        uses: vj-abigo/invite-on-label@v1.2
        with:
          organization: web3community 
          label: github-invitation
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          comment: '![welcome](https://user-images.githubusercontent.com/73097560/121835696-761b5c80-cd04-11eb-9d9c-6a4f6fb07724.gif)<br><b>Invitation sent to join the GitHub Organization. Welcome to Web3Community 🎉</b><br><br>Please check your mail to accept the invitation sent by the bot! 🤖<br><h1>About us</h1>An Open Source Community that focuses on decentralized applications, Web3, and Blockchain technologies 💻 Great to have you in our community ✨ Looking forward to your valuable contributions! 🤓 You can also check our community [socials](https://bio.link/web3community) ✨ 💛 You can also share about our community with other folks who want to learn Blockchain tech together in an inclusive environment 👉👈'
        env:
          INVITE_TOKEN: ${{ secrets.INVITE_TOKEN }}

